[package]
name = "msr"
description = "mastodon client in rust"
version = "0.0.2"
authors = ["syui <syui@syui.cf>"]
edition = "2021"

[dependencies]
seahorse = "*"
dotenv = "0.15"
mammut = "0.13.0"
serde_derive = "1.0"
serde_json = "1.0"
serde = "*"
config = { git = "https://github.com/mehcode/config-rs", branch = "master" }
shellexpand = "*"
curl = "*"
image = "*"
